version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    cooldown:
      semver-major-days: 28
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      rails:
        patterns:
          - "activesupport"
          - "activerecord"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    cooldown:
      default-days: 14
